appearance:
  content_width: 900
# Sidebar profile
profile:
  # é‚®ç®±ç”¨äºç”Ÿæˆ gravatar å¤´åƒï¼Œå¦‚é…ç½®äº† `hexo.config.email`ï¼Œæ­¤é¡¹å¯ç¼ºçœ
  email: coder101011@outlook.com

  # ä¹Ÿå¯ä»¥ç›´æ¥è®¾ç½®å¤´åƒ URL
  # avatar: https://cdn.jsdelivr.net/gh/hibichann/picgo@main/202305251546476.jpg
  avatar: /pfp.jpg

  # ä¸ªæ€§ç­¾å
  bio: A Front-end developer's Blog.
menu:
  ğŸ ä¸»é¡µ: /
  ğŸ§‘â€ğŸ’»å…³äº: /about
  ğŸ”æœç´¢: /search
  Github: https://github.com/hibichann
  RoboPunk: https://robopunk.pages.dev
  Krypt: https://krypt-test.pages.dev/
sns:
  email: coder101011@outlook.com
  github: https://github.com/hibichann
  twitter: https://twitter.com/misaka_level0
  telegram: https://t.me/hibichann
  qq: 321606998
category:
  # åˆ†ç±»é¡µåˆ†é¡µå¤§å°ï¼Œç¼ºçœå€¼ `10`
  per_page: 10
search:
  # åœ¨é¡µé¢å³ä¸‹è§’çš„ FAB æŒ‰é’®é‡Œæ˜¾ç¤ºå¿«æ·æœç´¢å…¥å£
  fab: true

  # é¢å¤–ç”Ÿæˆ search é¡µé¢ï¼Œå¯é…ç½®åœ¨ sidebar å¯¼èˆªï¼Œå¦‚ `Search: /search`
  page: true

  # ä»¥ä¸Šä¸¤ä¸ªå…¥å£å¿…é¡»è‡³å°‘è®¾ç½®ä¸€ä¸ªï¼Œå¦åˆ™è§†ä¸ºæ— æ•ˆé…ç½®

  # æœ¬åœ°æœç´¢ï¼Œå³ç”Ÿæˆæœ¬åœ° json æ–‡ä»¶
  adapter:
    # json æ•°æ®çš„èŒƒå›´ï¼Œæ•°ç»„
    range:
      - post
      - page

    # json æ•°æ®çš„æ¡ç›®é™åˆ¶
    # å‡å¦‚ `limit:1000`ï¼ŒåŒæ—¶æœ‰ 800 ç¯‡ postï¼Œ800 ç¯‡ pageï¼Œåˆ™æœ€ç»ˆç”Ÿæˆçš„æ•°æ®åŒ…å«ï¼š
    # 800 ç¯‡ postï¼Œ200 ç¯‡ page
    # ç¼ºçœå€¼ `10000`
    limit: 10000

    # æœç´¢ç»“æœåˆ†é¡µå¤§å°ï¼Œç¼ºçœå€¼ `10`
    per_page: 10
